# Generated by Django 2.2.19 on 2023-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='титл')),
                ('slug', models.SlugField(unique=True, verbose_name='адрес')),
                ('description', models.TextField(verbose_name='описание')),
            ],
        ),
    ]
