# Generated by Django 2.2.19 on 2023-05-07 20:24

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.Menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
        ),
    ]
