# Generated by Django 2.2.19 on 2023-05-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='active',
        ),
    ]
